/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qcom_wifi_QWifiLib */

#ifndef _Included_qcom_wifi_QWifiLib
#define _Included_qcom_wifi_QWifiLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qcom_wifi_QWifiLib
 * Method:    enableWifi
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_qcom_wifiservice_QWifiLib_enableWifi
  (JNIEnv *, jobject);

/*
 * Class:     qcom_wifi_QWifiLib
 * Method:    connect
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_qcom_wifiservice_QWifiLib_connect
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
